services:
  head:
    image: ray-sample:latest
    container_name: ray-head
    entrypoint: ["bash", "-c", "ray start \
      --head \
      --port=6379 \
      --dashboard-host=0.0.0.0 \
      --dashboard-port=8265 \
      --disable-usage-stats \
      --block"]
    ports:
      - "6379:6379"
      - "8265:8265"
    volumes:
      - .:/app  # ✅ FIXED

  worker:
    image: ray-sample:latest
    container_name: ray-worker
    depends_on:
      - head
    working_dir: /app
    entrypoint: ["bash", "/app/entrypoints/worker-entrypoint.sh"]

    volumes:
      - .:/app  # ✅ FIXED

  trainer:
    image: ray-sample:latest
    container_name: ray-trainer
    depends_on:
      - head
      - worker
    working_dir: /app
    entrypoint: ["bash", "/app/entrypoints/trainer-entrypoint.sh"]
    volumes:
      - .:/app  # ✅ FIXED
